import {escapeHTML as esc} from './app-model.js';

const number=(v,n=2)=>typeof v==='number'&&Number.isFinite(v)?v.toFixed(n):'—';
const timestamp=value=>{const d=new Date(value);return Number.isNaN(d.getTime())?'No timestamp':d.toLocaleString('en-GB',{timeZone:'UTC',dateStyle:'medium',timeStyle:'short'})+' UTC';};
const computer=`<svg viewBox="0 0 64 48" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><rect x="12" y="3" width="40" height="29" rx="3"/><path d="M12 32 4 42h56l-8-10M24 42h16"/><path d="M21 13h22M21 19h13" opacity=".4"/></svg>`;
const card=(label,value,detail)=>`<article class="cluster-metric"><span class="eyebrow">${esc(label)}</span><strong>${value}</strong><p>${esc(detail)}</p></article>`;

function inferenceResults(data){
  const test=data.inference_test||{},cases=Array.isArray(test.cases)?test.cases:[];
  if(!cases.length)return '';
  const maximum=Math.max(1,Number(test.local_tok_s)||0,Number(test.remote_tok_s)||0);
  const change=typeof test.change_percent==='number'?`${test.change_percent>0?'+':''}${number(test.change_percent,1)}%`:'—';
  return `<section class="panel"><div class="panel-head"><div><h2>GLM inference · first cluster test</h2><p>Measured model execution · ${esc(timestamp(test.created_at))}</p></div><span class="badge amber">Experimental · not promoted</span></div><div class="panel-body">
  <div class="info-note amber"><strong>${esc(test.verdict||'Qualification pending')}</strong></div><p class="chart-note">${esc(test.scope)}</p>
  <div class="cluster-predictions">${[['M5 internal SSD',test.local_tok_s],['Internal + M1 RAM',test.remote_tok_s]].map(([label,value])=>`<div class="cluster-prediction"><span>${esc(label)}<small>128 tokens · mean of two runs</small></span><div class="cluster-bar-track"><i style="width:${Math.max(0,Math.min(100,(Number(value)||0)/maximum*100))}%"></i></div><strong>${number(value,3)} <small>tok/s</small></strong></div>`).join('')}</div>
  <div class="cluster-metrics">${card('Decode change',change,'Remote versus matched local control')}${card('Generated output',test.identity_pass===true?'Identical':'Not verified','Compared byte for byte within each prompt')}${card('Remote payload',`${number(test.remote_bytes/1e9)} <small>GB</small>`,'All three remote arms; warm-up excluded')}${card('Selected-cache hits',`${number(test.cache_hit_rate*100,0)}<small>%</small>`,`${number(test.experts,0)} experts; not the full-model cache hit rate`)}</div>
  <details><summary>All ${cases.length} inference arms</summary><div class="table-scroll"><table class="tight-table"><thead><tr><th>Arm</th><th>Tokens</th><th>Decode tok/s</th><th>First byte, s</th><th>Remote GB</th><th>Output match</th></tr></thead><tbody>${cases.map(r=>`<tr><td>${esc(r.tag)}</td><td>${number(r.tokens,0)}</td><td>${number(r.decode_tok_s,4)}</td><td>${number(r.first_byte_s)}</td><td>${number(r.remote_bytes/1e9)}</td><td>${r.identity_pass===true?'Passed':'Not verified'}</td></tr>`).join('')}</tbody></table></div></details>
  <p class="chart-note">Local / remote / remote / local at 128 tokens, after a 60-token smoke pair. Four synchronous TCP lanes; every remote component checked with SHA-256. Warm-up ${number(test.warmup_seconds)} s is outside arm timing. ${test.servers_stopped?'The test server has stopped.':''}</p></div></section>`;
}

function pipelineResults(data){
  const test=data.pipeline_test||{},profiles=Array.isArray(test.profiles)?test.profiles:[];
  if(!profiles.length)return '';
  const maximum=Math.max(1,...profiles.map(r=>Number(r.transfer_gbs)||0));
  return `<section class="panel"><div class="panel-head"><div><h2>Queued transfers + shared RAM cache</h2><p>Latest transport campaign · ${esc(timestamp(test.created_at))}</p></div><span class="badge ${test.identity_pass?'green':'amber'}">${number(test.verified,0)} / ${number(test.requested,0)} verified</span></div><div class="panel-body">
  <p class="chart-note">${esc(test.scope)}</p><h3>1,000-record screening</h3><div class="cluster-predictions">${profiles.filter(r=>r.headline).map(r=>`<div class="cluster-prediction"><span>${esc(r.name)}<small>${number(r.repetitions,0)} runs · mean transfer rate</small></span><div class="cluster-bar-track"><i style="width:${Math.max(0,Math.min(100,(Number(r.transfer_gbs)||0)/maximum*100))}%"></i></div><strong>${number(r.transfer_gbs)} <small>GB/s</small></strong></div>`).join('')}</div>
  <p class="chart-note">Bars measure both paths over the same transfer interval, excluding SHA-256 time. The table also shows total time including verification.</p>
  <div class="table-scroll"><table class="tight-table"><thead><tr><th>Configuration</th><th>Cache hits</th><th>Transfer GB/s</th><th>With SHA-256 GB/s</th><th>Wall gain</th></tr></thead><tbody>${profiles.map(r=>`<tr><td>${esc(r.name)}</td><td>${number(r.cache_hit_rate*100,1)}%</td><td>${number(r.transfer_gbs,3)}</td><td>${number(r.wall_gbs,3)}</td><td>${r.gain_percent>0?'+':''}${number(r.gain_percent,1)}%</td></tr>`).join('')}</tbody></table></div>
  ${test.confirmed_transfer_gbs?`<h3 style="margin-top:24px">4,000-record confirmation</h3><div class="cluster-metrics">${card('Cached transfer',`${number(test.confirmed_transfer_gbs)} <small>GB/s</small>`,'Mean of two longer repeats; hashing excluded')}${card('With verification',`${number(test.confirmed_wall_gbs)} <small>GB/s</small>`,'Two SHA-256 workers; common wall interval')}${card('Cache gain',`+${number(test.confirmed_gain_percent,1)}<small>%</small>`,'Versus the matched longer pipelined control')}</div>`:''}
  <div class="info-note" style="margin-top:18px">One cache serves both cables. Trial budget: ${number(test.cache_limit_gib,0)} GiB; peak expert data: ${number(test.cache_peak_gib,2)} GiB. Cache buffers are ordinary pageable RAM. The application cache is off by default.</div>
  <details><summary>All ${(test.cases||[]).length} pipeline and cache arms</summary><div class="table-scroll"><table class="tight-table"><thead><tr><th>Arm</th><th>Verified</th><th>Transfer GB/s</th><th>With SHA-256 GB/s</th><th>Cache hits</th></tr></thead><tbody>${(test.cases||[]).map(r=>`<tr><td>${esc(r.name)}</td><td>${number(r.verified,0)}</td><td>${number(r.transfer_gbs,3)}</td><td>${number(r.wall_gbs,3)}</td><td>${number(r.cache_hit_rate*100,1)}%</td></tr>`).join('')}</tbody></table></div></details>
  <p class="chart-note">${esc(test.method)} ${test.servers_stopped?'Test daemon stopped; no remote cache currently allocated.':''} These transport measurements do not establish a token-speed gain or cold SSD ceiling.</p></div></section>`;
}

function measuredLinks(data){
  const test=data.network_test||{},cases=Array.isArray(test.cases)?test.cases:[];
  if(!cases.length)return '';
  const selected=cases.filter(r=>r.headline===true),peak=Math.max(1,...cases.map(r=>Number(r.wall_gbs)||0));
  const experts=Array.isArray(data.expert_test?.cases)?data.expert_test.cases:[];
  return `<section class="panel"><div class="panel-head"><div><h2>Measured cable bandwidth</h2><p>M1 → M5 · TCP · ${number(test.duration_seconds,0)} seconds per arm · ${esc(timestamp(test.created_at))}</p></div><span class="badge green">Independent paths verified</span></div><div class="panel-body">
  <div class="cluster-predictions">${selected.map(r=>`<div class="cluster-prediction"><span>${esc(r.label)}<small>${esc(r.streams)} TCP streams · final repeat</small></span><div class="cluster-bar-track"><i style="width:${Math.max(0,Math.min(100,(Number(r.wall_gbs)||0)/peak*100))}%"></i></div><strong>${number(r.wall_gbs)} <small>GB/s</small></strong></div>`).join('')}</div>
  <p class="chart-note">${esc(test.aggregate_method)} These are network-only measurements; no SSD reads or model execution.</p>
  <details><summary>All ${cases.length} network arms and route checks</summary><div class="table-scroll"><table class="tight-table"><thead><tr><th>Arm</th><th>TCP streams</th><th>Wall GB/s</th><th>Retransmits</th><th>Interface check</th></tr></thead><tbody>${cases.map(r=>`<tr><td>${esc(r.name)}</td><td>${esc(r.streams)}</td><td>${number(r.wall_gbs,3)}</td><td>${number(r.retransmits,0)}</td><td>${esc(r.interface_check)}</td></tr>`).join('')}</tbody></table></div></details>
  ${experts.length?`<h3 style="margin-top:26px">Real expert transfers</h3><p class="chart-note">${esc(data.expert_test.scope)}</p><div class="table-scroll"><table class="tight-table"><thead><tr><th>Path</th><th>Verified records</th><th>Including SHA-256, GB/s</th><th>Identity</th></tr></thead><tbody>${experts.map(r=>`<tr><td>${esc(r.name)}</td><td>${number(r.verified,0)} / ${number(r.requested,0)}</td><td>${number(r.wall_gbs,3)}</td><td>${r.identity_pass===true?'Passed':'Not passed'}</td></tr>`).join('')}</tbody></table></div>`:'<p class="chart-note">Expert transfer checks are pending.</p>'}
  </div></section>`;
}

export function clusterView(data){
  const node=data.node||{},network=data.network||{},s1=data.s1||{},s0=data.s0||{},pipeline=data.pipeline_test||{};
  const connected=Number.isInteger(network.connected_links)?Math.max(0,Math.min(3,network.connected_links)):0;
  const independent=Number.isInteger(network.independent_links)?Math.max(0,Math.min(connected,network.independent_links)):0;
  const scenarios=Array.isArray(s0.scenarios)?s0.scenarios:[];
  const max=Math.max(1,...scenarios.map(r=>Number(r.predicted_tok_s)||0));
  const verified=s1.identity_pass===true&&s1.verified===s1.requested&&s1.verified>0;
  return `<div class="page-heading"><div><div class="eyebrow">ARGODRIVE WIRE <span class="footer-dot">/</span> EXPERIMENTAL</div><h1>Cluster</h1><p>Keep compute local. Bring expert weights across the wire.</p></div><div class="button-group"><button class="button" data-action="refresh-cluster">Refresh evidence</button><button class="button primary" data-action="export-cluster">Export report</button></div></div>
  <div class="cluster-evidence-label"><span class="badge purple">Recorded test session</span><span>${data.source==='bundled_reference'?'Development test rig · bundled reference':'Local qualification report'} · ${esc(timestamp(data.captured_at))}</span><strong>${data.inference_test?.cases?.length?'Experimental engine tested · default off':'Remote inference not enabled'}</strong></div>
  ${network.note?`<div class="info-note amber" style="margin-bottom:18px">${esc(network.note)}</div>`:''}
  ${data.error?`<div class="info-note amber" role="alert">${esc(data.error)}</div>`:''}
  <div class="cluster-hero"><div class="cluster-hero-intro"><span class="eyebrow">ONE HOST. A SECOND EXPERT TIER.</span><h2>Prove the transfer.<br> Then expand the pool.</h2><p>Expert bytes move to the inference host. Layer execution stays on its GPU. Every stage needs evidence before promotion.</p><span class="badge ${verified?'green':'amber'}">${verified?'Transfer identity check passed':'Transport qualification in progress'}</span></div>
  <div class="cluster-map" role="img" aria-label="Recorded topology: ${connected} observed Thunderbolt cables; ${independent} independently measured data paths."><div class="cluster-machine">${computer}<strong>Inference host</strong><span>M5 Max · 128 GiB</span><small>Local GPU + local fallback</small></div><div class="cluster-links">${[0,1,2].map(i=>`<div class="cluster-link ${i<connected?'observed':'planned'}"><span>LINK ${i+1}</span><i></i><small>${i<independent?'40 Gb/s · independent path tested':i<connected?'TB4 · inventory confirmed':'Awaiting independent link'}</small></div>`).join('')}</div><div class="cluster-machine">${computer}<strong>${esc(node.name||'Expert node')}</strong><span>${esc(node.memory_gib?node.memory_gib+' GiB · file reader':'Awaiting inventory')}</span><small>${pipeline.cache_implemented?'Shared RAM cache: implemented':'RAM pool: not implemented'}</small></div></div></div>
  ${inferenceResults(data)}${pipelineResults(data)}${pipeline.profiles?.length?'<p class="chart-note">Earlier single-link reference, retained for comparison:</p>':''}<div class="cluster-metrics">${card('Record checks',verified?`${number(s1.verified,0)} <small>/ ${number(s1.requested,0)}</small>`:'—','SHA-256 against the trusted source manifest')}${card('One-link transfer',`${number(s1.transfer_gbs)} <small>GB/s</small>`,'Sequential GET time; hashing excluded')}${card('Transfer + verification',`${number(s1.wall_gbs)} <small>GB/s</small>`,'Wall rate, including SHA-256 checks')}${card(independent?'Independent paths':'Links observed',`${independent||connected} <small>/ 3 planned</small>`,independent?'Verified with per-interface transmit counters':'Cable inventory; no aggregate link qualification')}</div>
  <p class="chart-note">Measured with existing K3 expert files: ${number(s1.bytes/1e9,2)} GB transferred; ${number(s1.unique_verified,0)} distinct records selected from ${number(s1.indexed,0)} indexed. OS cache state was uncontrolled. No GLM decode gain is established.</p>${measuredLinks(data)}<div class="two-col equal"><section class="panel"><div class="panel-head"><div><h2>Qualification path</h2><p>Hardware evidence and implementation gates.</p></div></div><div class="panel-body cluster-gates">${(data.gates||[]).map(g=>`<div class="cluster-gate"><span class="cluster-stage">${esc(g.code)}</span><div><strong>${esc(g.title)}</strong><p>${esc(g.detail)}</p></div><span class="badge ${g.status==='passed'?'green':g.status==='partial'?'amber':'purple'}">${esc(g.status||'pending')}</span></div>`).join('')||'<p>No qualification report loaded.</p>'}</div></section>
  <section class="panel"><div class="panel-head"><div><h2>Node read probe</h2><p>Physical reads during a F_NOCACHE application probe.</p></div></div><div class="panel-body">${(data.ssd_probe?.results||[]).map(r=>`<div class="cluster-storage-row"><span>${number(r.streams,0)} stream${r.streams===1?'':'s'}</span><div><i style="width:${Math.max(0,Math.min(100,(Number(r.device_read_gbs)||0)/10*100))}%"></i></div><strong>${number(r.device_read_gbs)} GB/s</strong></div>`).join('')||'<p class="muted">No SSD baseline recorded.</p>'}<div class="table-scroll"><table class="tight-table"><thead><tr><th>Streams</th><th>Application GB/s</th><th>Device / app bytes</th></tr></thead><tbody>${(data.ssd_probe?.results||[]).map(r=>`<tr><td>${number(r.streams,0)}</td><td>${number(r.application_gbs)}</td><td>${number(r.device_to_application_ratio*100,1)}%</td></tr>`).join('')}</tbody></table></div><p class="chart-note">${esc(data.ssd_probe?.scope||'Rates must come from the node, not the sum of advertised link speeds.')}</p><div class="info-note" style="margin-top:20px">The cold tier shares one node SSD. More links increase available network bandwidth; they do not multiply SSD bandwidth.</div><div class="setting-line"><span>Receive path</span><strong>Caller-owned buffer</strong></div><p class="chart-note">Native recv writes into the final destination. Kernel and socket copies still occur. ${data.inference_test?.cases?.length?'The CLI trial uses existing Metal buffers with local overwrite after a failed remote read.':'Metal wrapping and engine fallback are pending.'}</p></div></section></div>
  <section class="panel"><div class="panel-head"><div><h2>Before-hardware prediction</h2><p>S0 sensitivity replay · ${number(s0.tokens,0)} recorded GLM steps · predictions, not benchmark results.</p></div><span class="badge amber">Assumed rates</span></div><div class="panel-body"><div class="info-note">${esc((s0.limitations||[])[0]||'No measured speed gain is established.')}</div><div class="cluster-predictions">${scenarios.map(r=>`<div class="cluster-prediction"><span>${esc(r.name)}<small>${number(r.links,0)} link${r.links===1?'':'s'}</small></span><div class="cluster-bar-track"><i style="width:${Math.max(0,Math.min(100,(Number(r.predicted_tok_s)||0)/max*100))}%"></i></div><strong>${number(r.predicted_tok_s,3)} <small>tok/s</small></strong></div>`).join('')}</div><p class="chart-note">Assumptions: 4.4 GB/s per link; 6 GB/s node SSD; 10 GB/s host SSD; 1 ms latency; 100 ms non-I/O time/token. No lookahead or compute overlap. Predictions are not directly comparable to the historical 3.70 tok/s champion.</p><details><summary>Model limitations and provenance</summary><p class="source-path">${esc(s0.source||'')} · SHA-256 ${esc(s0.source_sha256||'')}</p><ul>${(s0.limitations||[]).map(s=>`<li>${esc(s)}</li>`).join('')}</ul></details></div></section>
  <div class="info-note">${esc(data.notice||'Saved evidence only.')} ${data.inference_test?.cases?.length?'GLM integration is experimental. RDMA, engine request pipelining and admission by measured latency remain open.':pipeline.cache_implemented?'RDMA, hints and ds4 integration are future stages.':'RDMA, remote RAM caching, hints and ds4 integration are future stages.'}</div>`;
}
